### ISSUE TITLE
MRU not working after latest update

### ISSUE THREAD

**Issue by lukepass** [jlanzarotta/bufexplorer#108]
Hello, after the latest update the MRU sorting is not working anymore, most of the times the files in the buffer seem to be in a random order. I tried tinkering with options and reverse but it seems just "broken". Before the latest update is was working fine.

Maybe it's because of the following pull request?

Fix MRU sort order after loading vim session #107

Thanks!

**Comment by lukepass** [comment]
After downgrading to v7.4.24 all is working fine again. Thanks.

**Comment by jlanzarotta** [comment]
That is strange... Sorry for the delay... Let me check it out..

**Comment by jlanzarotta** [comment]
I am unable to reproduce this issue... Can you please provide me your steps you used to generate the issue?

**Comment by lukepass** [comment]
Before the downgrade, when pressing `<Leader>be` to open bufexplorer with 15-20 files and MRU, the order is not correct. If I edit a file, switch to another file and then open bufexplorer, the last used file is not always at the top (or at the bottom) of the list and the other files are not in the correct order either.
The behavior is not consistent, sometimes it works, it seems "random" but there is definitely something wrong. After downgrading to v7.4.24 the behavior is working again 100% of the times.

Thanks.

**Comment by jlanzarotta** [comment]
Interesting.  Thanks for the feedback.  I will keep trying to reproduce the issue and try to figure our a solution.

**Comment by lukepass** [comment]
I can confirm that it now works! Thanks.
