### ISSUE TITLE
Bufexplorer is slow when lots of buffers open

### ISSUE THREAD

**Issue by Uroc327** [jlanzarotta/bufexplorer#21]
When I start vim with multiple files, bufexplorer is perfectly fast.

When I've opened lots of files, then bufexplorer gets slower and slower until it's really hard to select the correct file as bufexplorer reacts extremely slow.

**Comment by Uroc327** [comment]
According to a vim profile these lines are the 'worst'

    function          count  total (s)   self (s)     line
    BufExplorer          55   3.951864   0.012892     silent let s:raw_buffer_listing = s:GetBufferInfo(0)
    BufExplorer          55   1.140781   0.000395     call s:DisplayBufferList()
    SelectBuffer         53  18.745413   0.062483             execute "keepalt keepjumps silent b!" _bufNbr
    DisplayBufferList    55   1.089410   0.001018     call s:BuildBufferList()
    GetBufferInfo     51695   0.724796   0.506957             call add(allwidths[n], s:StringWidth(b[n]))
    GetBufferInfo     51430   0.729095   0.515161                 call add(listedwidths[n], s:StringWidth(b[n]))

**Comment by ivegotasthma** [comment]
I'm experiencing this as well.

**Comment by jlanzarotta** [comment]
Sorry, I have not come up with a solution on this yet...

**Comment by ivegotasthma** [comment]
I think I solved it on my fork, you can check it out. I've been using it
for more than a month I think.

**Comment by johndgiese** [comment]
I'm also experiencing this slowdown.

**Comment by ivegotasthma** [comment]
I think I fixed it on my fork, check it out to see if that fixes it. I
told the maintainer about it as well but he doesn't seem interested or
doesn't like the fix.

**Comment by jlanzarotta** [comment]
Hi,
Sorry about that.  I did not see your comment until just now as I was going through some old emails...  I will take a look at your fix hopefully today and get back with you...

**Comment by jlanzarotta** [comment]
Looks like a reasonable patch.  Just two line changed.  I have made the change locally and will give it a try over the next few days and report back.

Thanks again for the patch and sorry for the delay in responding back.

**Comment by jlanzarotta** [comment]
So far so good on the patch.  I hope to have a new version submitted this week.

**Comment by ivegotasthma** [comment]
@jlanzarotta Thanks for mentioning me in the patch. This issue can be closed now, right?

**Comment by jlanzarotta** [comment]
yeap, it can be closed...  I am still not used to github :)

**Comment by Uroc327** [comment]
Hmm.. Sorry for being quiet the last few months, but the issue does not seem fixed to me :/
I still experience the same problem as stated in the first post.
