### ISSUE TITLE
Add Toggle command

### ISSUE THREAD

**Issue by PhilRunninger** [jlanzarotta/bufexplorer#23]
*This is a reissue of pull request #22, after I'd mistakenly deleted by branch.*

I added the following things to toggle the BufExplorer list on and off.

the command ```:ToggleBufExplorer```
the map ```<Leader>bt```, and
the function ```ToggleBufExplorer()```
The function works by simply calling the ```BufExplorer()``` or ```s:Close()``` function, depending on the current state of BufExplorer. Now one can easily see which buffers are open (with a mapped function key, ideally), and then easily close the buffer list with the same key.

I believe this pull request will satisfy the request in Issue #3.

**Comment by jlanzarotta** [comment]
Thanks Phil, I will check it out.

**Comment by PhilRunninger** [comment]
My bad. I thought I was recreating a pull request, not creating an issue. Do I need to create a new PR?

**Comment by PhilRunninger** [comment]
Never mind. I figured it out #22 is reopened. Thanks for looking at it, and for putting up with my Github missteps.
