### ISSUE TITLE
Error message on Close after deleting buffers.

### ISSUE THREAD

**Issue by PhilRunninger** [jlanzarotta/bufexplorer#25]
I'm getting an error message (see below) intermittently when I close BufExplorer. It occur only after I've wiped one or more buffers, using the D key, but not every time.
```
Error detected while processing function <SNR>19_SelectBuffer..<SNR>19_Close:
line 17:
E86: Buffer 14 does not exist
```
I will do some investigating on my own, including tracking down the exact steps needed to reproduce the error.

**Comment by PhilRunninger** [comment]
Jeff, 
I discovered that the error occurs when you delete the buffer that was active when BufExplorer was started. There seem to be no side effects, aside from the messages. It appears to be caused by the code from pull request #15, which Philip has requested to be reverted (in pull request #24).

**Comment by jlanzarotta** [comment]
I will try and fix this.  I originally was trying to use git from the command line and struggling quite a bit.  I am trying to get the Windows GitHub software installed to hopefully make the updating of the code easier...
