### ISSUE TITLE
[RFC] Key bindings broken in Vim 7.3 without patch1261

### ISSUE THREAD

**Issue by rfc1459** [jlanzarotta/bufexplorer#36]
#33 added `<nowait>` to all bindings to address tpope/vim-surround#98, but that option is only available in Vim 7.3 with patch 1261 and later.

I still have systems with Ubuntu 12.04 around and it ships Vim 7.3 *without* patch 1261 and bufexplorer is effectively useless on such systems.

The most straightforward approach would be something along the lines of this snippet (other bindings omitted):
```viml
if v:version > 703 || v:version == 703 && has('patch1261')
    let map_nw = '<nowait> '
else
    let map_nw = ''
endif

execute 'nnoremap <script> <silent> ' map_nw '<buffer> d             :call <SID>RemoveBuffer("delete")<CR>'
```
This would restore the key bindings, but would also reintroduce the delay on pre-7.3 Vim and 7.3 Vim without patch1261.

Given that waiting a couple of seconds when hitting 'd' is a minor nuisance compared to complete loss of all bindings, I would say that this is worth fixing, but I'd like to get some feedback before filing the PR.

**Comment by jlanzarotta** [comment]
Hi,
I have applied your update locally and all seems to be working well; however, I am using 7.4...

**Comment by rfc1459** [comment]
I'm using 7.4 as well on _most_ of my machines, that's because I asked for feedback before filing a formal PR.

Given that nobody except you and me chimed in on this issue, I suppose most people moved off 7.3 (shame on Ubuntu for neglecting patch 1261!), so there's no need to patch bufexplorer - except for me, that is :-)

Sorry for the noise.

**Comment by jlanzarotta** [comment]
I see no reason not to add your code to protect older versions of vim...

**Comment by rfc1459** [comment]
Code bloat, mostly. I'm a bit sensitive on that part.
Either way, if you feel so inclined I'll send a PR as soon as I have access to my (patched) sources.
