### ISSUE TITLE
Set filetype

### ISSUE THREAD

**Issue by adelarsq** [jlanzarotta/bufexplorer#41]
Can be the filetype be setted to something like bufexplorer? So custom autocomands can be used.

**Comment by jlanzarotta** [comment]
hum, yeah, I think that is possible.  Let me check into that.

**Comment by bluz71** [comment]
+1

I to want to do autocmd processing based on the FileType attribute.

NERDtree sets their filetype to 'nerdtree'.
Currently this plugin does not set a filetype. It seems reasonable to set it to 'bufexplorer' as suggested.

**Comment by jlanzarotta** [comment]
Sounds like a reasonable request.  Let me look into it.

**Comment by jlanzarotta** [comment]
Okay, It is in.  I will commit these changes...

**Comment by jlanzarotta** [comment]
Now in release v7.4.14.

**Comment by bluz71** [comment]
Superb.

This is a very useful enhancement to this excellent plugin.

Thank you!

**Comment by jlanzarotta** [comment]
You are very welcome.
