### ISSUE TITLE
When using <leader>bv can the selected buffer be opened in the new split?

### ISSUE THREAD

**Issue by CrashyBang** [jlanzarotta/bufexplorer#44]
When using <leader>bv can the selected buffer be opened in the new split?

So if I open a new vertical split with bufexplorer and select a buffer can it fill the vertical split that was opened?

Does that make sense?

Cheers,
Otis.

**Comment by yubo56** [comment]
I was skimming through issues to see whether this was asked anywhere, I threw together something that works for me at https://github.com/yubo56/bufexplorer. If you hit anything that doesn't work, I can try my best to fix but I'm not at all adept with vimscript :joy:

**Comment by jlanzarotta** [comment]
Hello,

Would the "f" (toggles whether you are taken to the active window when selecting a buffer or not.) possible work for you?  While in bufexplorer, press the "f" key to toggle this.  If that does work, you could set the global option, "g:bufExplorerFindActive" to 0 to permanently turn this feature off...  You would put the following in your vimrc file... "let g:bufExplorerFindActive=0".

**Comment by jlanzarotta** [comment]
This has now be implemented in the latest version...
