### ISSUE TITLE
line 69, ^M is not a editor command

### ISSUE THREAD

**Issue by wendy260310** [jlanzarotta/bufexplorer#45]
I use the latest version (7.4.9).When I open vim,error noticed as the title said.Could someone helps me?
My vim is VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:32)
and my os is 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by wendy260310** [comment]
I changed to 7.4.6  and is ok

**Comment by jlanzarotta** [comment]
Grrr ^m!  Sorry about that, let me take a look at it...

**Comment by jlanzarotta** [comment]
Could you download a release 7.4.9 again and see if that works for you?  I think I have fixed it.  I am definitely a git amateur.

**Comment by wendy260310** [comment]
Ha,I download 7.4.9 and it works fine.Thank you very much

**Comment by jlanzarotta** [comment]
Fantastic!  You are welcome.  Sorry for inconvenience.  Glad it worked...

**Comment by jlanzarotta** [comment]
Fixed in the latest release.
