### ISSUE TITLE
set nonumber doesn't work

### ISSUE THREAD

**Issue by devakivamsi** [jlanzarotta/bufexplorer#49]
I'm using BufExplorer via WinManager with all the defaults. I still see line numbers in the bufexploer.
Vim version 7.4 patched up to 629.

Thanks,
Vamsi

**Comment by jlanzarotta** [comment]
Okay, let me check this out.

**Comment by jlanzarotta** [comment]
I looked into this a bit.  I am not able to reproduce this; however, I am on the latest and greatest Vim 8.0 with all patches...

What version of bufexplorer are you using?  I assume 7.4.12?

**Comment by devakivamsi** [comment]
I've tried this on centos 6.8 & mac os 10.12

Sample from MAC
:ver
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 28 2017 06:11:03)
MacOS X (unix) version
Included patches: 1-386
Compiled by Homebrew

![screen shot 2017-03-01 at 9 51 56 pm](https://cloud.githubusercontent.com/assets/8160763/23494727/5b3439a4-fec9-11e6-98c8-f5c89eb8c398.png)

my .vimrc
$ cat .vimrc
syntax on
filetype plugin indent on
set t_Co=256 background=dark
set number
set cindent tabstop=4 softtabstop=4 shiftwidth=4 expandtab

$ find .vim
.vim
.vim/.netrwhist
.vim/doc
.vim/doc/bufexplorer.txt
.vim/doc/winmanager.txt
.vim/plugin
.vim/plugin/bufexplorer.vim
.vim/plugin/winfileexplorer.vim
.vim/plugin/winmanager.vim
.vim/plugin/wintagexplorer.vim

**Comment by jlanzarotta** [comment]
Hum...

**Comment by jlanzarotta** [comment]
Okay, I see what you are saying.  I will check further into what is going on and let you know.

Thanks,

**Comment by devakivamsi** [comment]
Thank you.
I've tried to "set nonumber" in bufexplorer.vim and it would still use the "set number" from .vimrc

I'd like to be able to not have numbers show up in bufexplorer buffer.

**Comment by jlanzarotta** [comment]
bufexplorer already turns the numbers off by using the _setlocal nonumber_ command.  The strange thing is that this seems to have no effect when using WinManager...

**Comment by jlanzarotta** [comment]
Ah, I think I know what the issue is.  In the Initialize() method, I call _setlocal nonumber_.  The only time Initialize() is called is with an _autocmd BufWinEnter \[BufExplorer\]_ within bufexplorer itself.  In your example screenshot, the bufexplorer window name was "Buf List"...  I suspect this is the issue because the window names do not match.

**Comment by jlanzarotta** [comment]
Okay, give this attached version a try.  If it works for you, I will commit the changes and create a new version.
[bufexplorer.zip](https://github.com/jlanzarotta/bufexplorer/files/818059/bufexplorer.zip)

**Comment by devakivamsi** [comment]
The patch fixes the issue for me.

<img width="217" alt="screen shot 2017-03-06 at 10 30 32 am" src="https://cloud.githubusercontent.com/assets/8160763/23623755/096ab53e-0258-11e7-892b-199122712ce7.png">

Thank you!

**Comment by jlanzarotta** [comment]
Can you please try this attached version and see if it still works for you?  Thanks.  The previous version caused an issue with bufexplorer when run normally with winmanager.

[bufexplorer.zip](https://github.com/jlanzarotta/bufexplorer/files/824584/bufexplorer.zip)

**Comment by devakivamsi** [comment]
The new patch too works fine for me.

**Comment by jlanzarotta** [comment]
This has been patched.
