### ISSUE TITLE
Feature Request: Ability to refresh list

### ISSUE THREAD

**Issue by derwentx** [jlanzarotta/bufexplorer#58]
I'm pretty new to Vim, but I'm still clinging on to the concept of a persistent interface element that gives me information about the buffers that I have open. 
I haven't been able to develop that mental facilities to keep track of what's happening with all my buffers in my own head yet, so the idea is to have a persistent bufexplorer window that refreshes itself with some mechanism (that I hope to create myself).
If I delete a buffer outside of bufExplorer after opening bufExplorer, there is no apparent way to refresh it. I've tried `r` `r`, and a few other commands but nothing works. If I do :bufExplorer in the bufExplorer window i get a "Escaped\nWHAT THE 1\nWHAT THE 2\n".
Any help in creating a mechanism to refresh the buffer list would be awesome. I'm completely new to Vim scripting but can learn.

Thanks

**Comment by derwentx** [comment]
It looks like MiniBufExplorer handles this feature pretty well, but I would prefer to have a vertical list of buffers like BufExplorer has.

**Comment by jlanzarotta** [comment]
Might I suggest you look into the winmanager plugin.  There are several version now.  bufexplorer has capabilities to interact with winmanager, which might be just what you are looking for.  If not, let me know...

winmanager can be found:
http://www.vim.org/scripts/script.php?script_id=95
http://www.vim.org/scripts/script.php?script_id=1440
https://github.com/vim-scripts/winmanager--Fox

**Comment by derwentx** [comment]
Thanks for the tip. MiniBufExplorer turned out to be quite unstable but I found the plugin Ctrl-P did pretty much what I wanted, without the persistence (which I didn't mind losing) :D

**Comment by jlanzarotta** [comment]
You are welcome.  I am not familiar with the Ctrl-P plugin.

**Comment by jlanzarotta** [comment]
derwentx, did WinManager give you the functionality you needed?  If so, can I close this issue?

**Comment by derwentx** [comment]
go ahead :P




Derwent, 
Web Developer
laserphile.com <http://dev.laserphile.com/>

**Comment by jlanzarotta** [comment]
Thanks.

**Comment by jlanzarotta** [comment]
Thanks.
