### ISSUE TITLE
g:bufExplorerShowTabBuffer is not working correctly.

### ISSUE THREAD

**Issue by MarioRicalde** [jlanzarotta/bufexplorer#6]
Lets say you have 2 tabs:

Tab 1

    File1.txt
    File2.txt

Tab 2

    File3.txt
    File4.txt

When I switch to Tab 2 and trigger bufexplorer, I expect to see:

    File3.txt
    File4.txt

And I get

    File3.txt
    File4.txt

I change to tab 1 and I get

    File1.txt
    File2.txt
    File3.txt

I change to Tab 2 and I get

    File1.txt
    File3.txt
    File4.txt

There's something definitely wrong there.

**Comment by jlanzarotta** [comment]
Fixed in release 7.4.11.
