### ISSUE TITLE
Opening buffer in a new tab doesn't work (vim8)

### ISSUE THREAD

**Issue by EVODelavega** [jlanzarotta/bufexplorer#62]
Looking at the code, I think `execute "999tab split +buffer" . _bufNbr` should be changed to `execute "tab split +buffer" . _bufNbr`. Currently opening a buffer in a new tab results in _"E16: Invalid range: 999tab split +buffer <bufNbr>"_

https://github.com/jlanzarotta/bufexplorer/blob/d42be270a5c96cf41a741c84a53be7062695d085/plugin/bufexplorer.vim#L829

**Comment by jlanzarotta** [comment]
Thanks for the update.  I will look into this and apply your patch as soon as I can.

**Comment by jlanzarotta** [comment]
This has been fixed quite sometime ago, I just did not apply the patch and release it.  Version 7.4.18, which has now been release, should address this issue for you.  If it does not, please let me know.

Thanks,
