### ISSUE TITLE
Error detected while processing function <SNR>40_BESelectBuffer

### ISSUE THREAD

**Issue by snsnsjsn** [jlanzarotta/bufexplorer#77]
hi , when i list buffers and want to open somebuffer in new tab with key t, show this error .
my version is 
" Version number                                                                
   41 let g:bufexplorer_version = "7.2.8"
![image](https://user-images.githubusercontent.com/11435527/49325840-f41f1a00-f583-11e8-8371-a6660de57e43.png)

**Comment by jlanzarotta** [comment]
Is there anyway you can update to the latest version and see if it still happens?

**Comment by snsnsjsn** [comment]
it is ok now , i don't know how ,maybe reinstall system to latest ubuntu 18.04 and update vim to latest 8.1 。 
thanks

**Comment by snsnsjsn** [comment]
and my bufexplorer version is 7.4.20.
i use echo bufexplorer_version command in vim 
![image](https://user-images.githubusercontent.com/11435527/52930837-093a6680-3385-11e9-9d4a-540deee136e1.png)

![image](https://user-images.githubusercontent.com/11435527/52930829-02abef00-3385-11e9-9e26-353e415ac443.png)
