### ISSUE TITLE
Is there a shortcut to go previous/next buffer?

### ISSUE THREAD

**Issue by jetm** [jlanzarotta/bufexplorer#89]
Thank you for this great plugin.

I have read the documentation and I was unable to found a solution for the following problem. I would like to use a bufexplorer map where I could go to the previous/next buffer. What I do is to open the bufferexplorer list a look the buffer to open. I found this way too long, if a shortcut would exist.

**Comment by shepard8** [comment]
[This page](https://vim.fandom.com/wiki/Easier_buffer_switching#Plugins) recommends the following mappings:

```
" Buffers - explore/next/previous: Alt-F12, F12, Shift-F12.
nnoremap <silent> <M-F12> :BufExplorer<CR>
nnoremap <silent> <F12> :bn<CR>
nnoremap <silent> <S-F12> :bp<CR>
```
